import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Abhivyakti 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel='icon' href='../public/favicon.ico'></link>
      </Head>
      <div className={styles.hero}>
        <div>
          abhivyakti 2023 coming soon ...
        </div>
      </div>
    </>
  )
}
